Auth&token&passwordhash
bohdanlisovskyi/SSU-Golang-252-Chat pull request #13
Opened 2017-08-02 09:49 UTC by Greckas

merged remote master & add my functional with password hash and token

2017-08-02 18:03 UTC, 8tomat8 requested changes

2017-08-02 18:03 UTC, 8tomat8 commented on database/db-sqllite.go
> +	sqlLite *gorm.DB
Why this variable calls `sqlLite`? It would be better to give it some common name like `db` or `connection` etc.

2017-08-02 18:03 UTC, 8tomat8 commented on server/auth/login.go
> +func byQuery(db *gorm.DB) (*User, error) {
You don't have to create separate func for this it is absolutely not common functionality.

2017-08-02 18:03 UTC, 8tomat8 commented on server/auth/login.go
> +func ByName(UserName string) (*User, error) {
Try to name funcs with names that will describe functionality. For example this could be named `GetUserByName` or `UserByName`

2017-08-02 18:03 UTC, 8tomat8 commented on server/auth/login.go
> +func ByName(UserName string) (*User, error) {
And I don't think that it need to be exportable.

2017-08-02 18:03 UTC, 8tomat8 commented on server/auth/login.go
> +func Login(username, password string) error {
This method should also return some token. So far it could be hardcoded

2017-08-02 18:03 UTC, 8tomat8 commented on server/auth/registration.go
> +func NewUser(user *User, UserName, Password string) error {
By convention this methods with names which starts with `New[SomeType]` should create and return `SomeType`

2017-08-02 18:03 UTC, 8tomat8 commented on server/auth/login.go
> +	err2 := bcrypt.CompareHashAndPassword(
`New folder` and `New folder(2)`...

2017-08-02 18:03 UTC, 8tomat8 commented on server/auth/registration.go
> +	} else {
This `else` statement could be removed.

2017-08-02 18:03 UTC, 8tomat8 commented on server/auth/registration.go
> +func NewUser(user *User, UserName, Password string) error {
And I really don't understand what this function should do.

2017-08-02 18:03 UTC, 8tomat8 commented on server/core/server-core.go
> +				conn.Close()
This line could be removed.You already have this call in `defer`

2017-08-02 18:03 UTC, 8tomat8 commented on server/core/server-core.go
> +		loger.Log.Error("Add new connection error: %s", err)
Change to `Errorf()` or remove `%s`

2017-08-02 18:03 UTC, 8tomat8 commented on server/core/server-core.go
> +		if _, ok := clients[message.Header.UserName]; ok {
What difference between this one and previous one type? Code looks pretty the same.

2017-08-02 18:03 UTC, 8tomat8 commented on server/core/server-core.go
> +func addNewConnect(w http.ResponseWriter, r *http.Request) (*websocket.Conn, error) {
Should be called `NewConnect`

2017-08-03 06:44 UTC, Greckas commented on server/auth/login.go
> +func ByName(UserName string) (*User, error) {
fixed

2017-08-03 06:44 UTC, Greckas commented on database/db-sqllite.go
> +	sqlLite *gorm.DB
fixed

2017-08-03 06:49 UTC, Greckas commented on server/auth/login.go
> +func Login(username, password string) error {
I am with Volodymyr decided to write token into client connection, and appropriate every time user log on

2017-08-03 06:52 UTC, Greckas commented on server/auth/login.go
> +	err2 := bcrypt.CompareHashAndPassword(
fixed

2017-08-03 17:40 UTC, 8tomat8 requested changes

2017-08-03 17:40 UTC, 8tomat8 commented on server/auth/config.json
> +{
This file should be stored in `server` folder and not in `server/auth`

2017-08-03 17:40 UTC, 8tomat8 commented on server/auth/login.go
> +	if db_search == nil {
You can remove this check. It is excess

2017-08-03 17:40 UTC, 8tomat8 commented on server/auth/login.go
> +		return nil, err
You can remove this return

2017-08-03 17:40 UTC, 8tomat8 commented on server/auth/registration.go
>  		loger.Log.Errorf("no such user in db", err)
I thought that on registration user should not exist... So this is valid case.

2017-08-03 17:40 UTC, 8tomat8 commented on server/auth/registration.go
>  		loger.Log.Errorf("no such user in db", err)
[Read this article](http://jinzhu.me/gorm/advanced.html). There is good example for this case.

2017-08-03 17:40 UTC, 8tomat8 commented on server/auth/registration.go
> +	token := randToken()
`Login()` will return you a token. You have not to generate it manualy

2017-08-03 17:40 UTC, 8tomat8 commented on server/auth/registration.go
> +	Login(user.UserName, user.Password)
SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!

2017-08-03 17:40 UTC, 8tomat8 commented on server/auth/registration_test.go
> +	fmt.Println(user, token, err)
It is not a test.You should check if data were stored properly in DB and user was added to clients list.

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +//в коннект записати меседж для відправки на клієнт
Как раз самое время.

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +				conn.Close()
Not fixed

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +		auth.RegisterNewUser(x)
Why you register user after adding to clients list?

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +		//call register
Remove redundant comments from all over the code

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
>  			clients[message.Header.UserName] = Client{conn: conn}
Where is token?

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +			ok := Client{token: request_token}
Which token do you expect from user that was not authorized so far?

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +			// треба подумати над порівнянням токенів
Подумай очень хорошо. Тут опять ад.

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +			request_token := message.Header.Token
It will be empty in ALL cases

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +			if ok.token != request_token {
Why are you comparing same values?

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +			_, tok, _ := auth.Login(x.UserName, x.Password)
SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!SKIPPED ERROR CHECK!!!!!!!!!!!!

2017-08-03 17:40 UTC, 8tomat8 commented on server/core/server-core.go
> +	// TODO: Add token check
Please add it in this pull request.

2017-08-06 23:03 UTC, justakit requested changes

2017-08-06 23:03 UTC, justakit commented on server/auth/login.go
> +	err2 := bcrypt.CompareHashAndPassword(
Is it necessary to create `err2`, or better use `err` again?

2017-08-06 23:03 UTC, justakit commented on server/auth/login.go
> +	userPassword2 := password
Where is first one?
And why we need copy of `password`?

2017-08-06 23:03 UTC, justakit commented on server/auth/login.go
> +	hashFromDatabase := hash
The same question. Why we create copy of `hash`?

2017-08-06 23:03 UTC, KitlerUA commented on server/core/server-core.go
> +				Body:   newMessageBody,
Cannot use newMessageBody (type MessageBody) as type json.RawMessage

2017-08-06 23:03 UTC, KitlerUA commented on server/core/server-core.go
>  			var x *messageService.User
[Find x](https://static.fjcdn.com/pictures/Find+x_30c251_5488082.jpg)

2017-08-07 04:12 UTC, 8tomat8 requested changes

2017-08-07 04:12 UTC, 8tomat8 commented on server/auth/login_test.go
> +	fmt.Println(user, token, err)
What have you checked in this test?

2017-08-07 04:12 UTC, 8tomat8 commented on server/auth/registration.go
> +	if checkUsername(user.UserName) != true {
Could be moved with `if !checkUsername(user.UserName) {`

2017-08-07 04:12 UTC, 8tomat8 commented on server/auth/registration.go
> +	_, _, err = Login(user.UserName, user.Password)
Why are you ignoring token here?

2017-08-07 04:12 UTC, 8tomat8 commented on server/core/server-core.go
> +	if message.Header.Type_ == "message" {
Why have you added `message` for second time?

2017-08-07 04:12 UTC, 8tomat8 commented on server/core/server-core.go
>  	if message.Header.Type_ == "register" {
`register` was not fixed

2017-08-07 04:12 UTC, 8tomat8 commented on server/core/server-core.go
> +			us, tok, err := auth.Login(x.UserName, x.Password)
Please explain me, why are you always skip errors? Is it so hard to remember?

2017-08-07 04:12 UTC, 8tomat8 commented on server/core/server-core.go
>  			clients[message.Header.UserName] = Client{conn: conn, token: tok}
Even when login was not success?

2017-08-08 07:52 UTC, 8tomat8 requested changes

2017-08-08 07:52 UTC, 8tomat8 commented on server/auth/login.go
> +	defer db.Close()
It is not good idea... On second call of this function you will get closed connection.

2017-08-08 07:52 UTC, 8tomat8 commented on server/auth/registration.go
> +	defer db.Close()
Same as previous

2017-08-08 07:52 UTC, 8tomat8 commented on server/core/server-core.go
> +			} else {
Useless `else`

2017-08-08 07:52 UTC, 8tomat8 commented on server/core/server-core.go
> +		clients[message.Header.UserName] = Client{conn: conn}
Why don't you add `tok` to `Client`?

2017-08-08 07:52 UTC, 8tomat8 commented on server/core/server-core.go
> +		} else {
Useless `else`

2017-08-08 07:52 UTC, 8tomat8 commented on server/core/server-core.go
> +			if clientToken.token != message.Header.Token {
Move all this check to separate method. It's already mess here.
As I remember, we talked about method `Verify` in `auth` package

2017-08-08 07:52 UTC, 8tomat8 commented on server/core/server-core.go
> +				} else {
Useless `else`

2017-08-08 07:52 UTC, 8tomat8 commented on server/core/server-core.go
> +		} else {
Useless `else`

2017-08-08 07:52 UTC, 8tomat8 commented on server/core/server-core.go
>  	}
Try to run `make code-quality`... This method complexity is too high.

2017-08-10 08:26 UTC, 8tomat8 requested changes

2017-08-10 08:26 UTC, 8tomat8 commented on server/auth/login.go
> +func VerifyToken(clientToken, serverToken string) (bool, error) {
Why are you receiving strings? As I remember we were talking about `Client + Message`

2017-08-10 08:26 UTC, 8tomat8 commented on server/core/server-core.go
> +func ReturnPort() string {
Why can't you use `config.GetConfig().Server.Port` directly?

2017-08-10 08:26 UTC, 8tomat8 commented on server/modules/modules.go
> +	customers.Clients[message.Header.UserName] = customers.Client{Conn: conn, Token: tok}
We should add `conn.Close()` for those cases when we don't get to this line.

2017-08-10 08:26 UTC, 8tomat8 commented on server/core/server-core_test.go
> +	log.Printf("connecting to %s", u.String())
Don't use log in tests

2017-08-10 08:26 UTC, 8tomat8 commented on server/modules/modules.go
> +	customers.Clients[message.Header.UserName] = customers.Client{Conn: conn, Token: tok}
We should add `conn.Close()` for those cases when we don't get to this line.

2017-08-10 08:26 UTC, 8tomat8 commented on server/modules/modules.go
> +		Command:  "registrissucc",
Why authorization and registration methods have the same Command?

2017-08-10 09:52 UTC, 8tomat8 commented on server/core/server-core_test.go
> +	fmt.Println("connecting to %s", u.String())
`%s` will not be replaced when you using `fmt.Println`.
You should use `t.Logf()` or `fmt.Printf()`

2017-08-10 12:08 UTC, 8tomat8 approved these changes

2017-08-10 12:32 UTC, justakit approved these changes

2017-08-10 14:07 UTC, merged