Message api
bohdanlisovskyi/SSU-Golang-252-Chat pull request #2
Opened 2017-07-15 13:48 UTC by YAWAL

Basic functionality for message service.

2017-07-16 12:46 UTC, 8tomat8 requested changes

2017-07-16 12:46 UTC, 8tomat8 commented on messageService/message.go
> +	var dataStructure interface{}
dataStructure can be declared as map[string]interface{} to avoid excess assertion on 56 line

2017-07-16 12:46 UTC, 8tomat8 commented on messageService/message.go
> +func GetType(byteSlice [] byte) (string, error) {
It would be more efficient to unmarshall json to Message struct and then extract all required values.

2017-07-16 12:46 UTC, 8tomat8 commented on messageService/message.go
> +		if k == "type" {
JSONMap of type map[string]interface{} , why you can simply get value by key?
For example:
`valInterface, ok := JSONMap["type"]`
`if ok { value, ok := valInterface.(string) } `

2017-07-16 12:46 UTC, 8tomat8 commented on messageService/message.go
> +	JSONMap, err := UnmarshalAnyDataStructure(byteSlice)
It would be more efficient to unmarshall json to Message struct and then extract all required values.

2017-07-16 12:46 UTC, 8tomat8 commented on messageService/message.go
> +	for k, v := range JSONMap {
Same as previous

2017-07-16 12:46 UTC, 8tomat8 commented on messageService/message_test.go
> +		fmt.Println("TestMarshalMessage: PASS, Error-> ", err)
In tests you should use `t.Error()` or `t.Fatal()`, not `fmt.Println()`.
And try to avoid excess output like "=========...==="

2017-07-16 12:46 UTC, 8tomat8 commented on messageService/message_test.go
> +		fmt.Println("TestMarshalMessage: PASS, Error-> ", err)
Same for all tests

2017-07-17 14:44 UTC, YAWAL commented on messageService/message.go
> +	var dataStructure interface{}
Done

2017-07-17 14:45 UTC, YAWAL commented on messageService/message.go
> +func GetType(byteSlice [] byte) (string, error) {
Function for retrieving type from any request has been fixed.

2017-07-17 14:45 UTC, YAWAL commented on messageService/message.go
> +		if k == "type" {
Done

2017-07-17 14:46 UTC, YAWAL commented on messageService/message.go
> +	JSONMap, err := UnmarshalAnyDataStructure(byteSlice)
Function for retrieving command from any request has been fixed.

2017-07-17 14:46 UTC, YAWAL commented on messageService/message.go
> +	for k, v := range JSONMap {
Done

2017-07-17 14:47 UTC, YAWAL commented on messageService/message_test.go
> +		fmt.Println("TestMarshalMessage: PASS, Error-> ", err)
Done, tests have been refactored without using fmt.Println()

2017-07-17 18:06 UTC, 8tomat8 requested changes

2017-07-17 18:06 UTC, 8tomat8 commented on messageService/message.go
> +		log.Fatal("Error has occured: ", err)
log.Fatal will call panic() and your application will be stoped

2017-07-17 18:06 UTC, 8tomat8 commented on messageService/message.go
> +	typeInterface := unmarshaledRequest["type"]
Better use second returned value to check if key exists
For example:
`typeInterface, ok := unmarshaledRequest["type"]`
`ok` will be bool value

2017-07-17 18:38 UTC, YAWAL commented on messageService/message.go
> +		log.Fatal("Error has occured: ", err)
Fixed, changed to log.Println

2017-07-17 18:40 UTC, LisovskyiB commented on messageService/message.go
> +		log.Fatal("Error has occured: ", err)
я дописую роботу із бібліотекою по логрус, будемо всі її юзати. за кілька хв залию

2017-07-17 18:41 UTC, YAWAL commented on messageService/message.go
> +	typeInterface := unmarshaledRequest["type"]
Done.  bool value has been added to functionality

2017-07-18 17:35 UTC, 8tomat8 approved these changes

2017-07-18 17:42 UTC, bohdanlisovskyi reviewed
Done

2017-07-18 17:50 UTC, merged