Settings on server
bohdanlisovskyi/SSU-Golang-252-Chat pull request #25
Opened 2017-08-09 17:24 UTC by YAWAL

Functionality for settings has been completely rewritten according to changes on server as we discussed today

2017-08-10 17:33 UTC, 8tomat8 requested changes

2017-08-10 17:33 UTC, 8tomat8 commented on settingService/blockUser.go
> +func IsUserBlocked(request *messageService.Message) (isBlocked bool, err error) {
You defined `isBlocked` and `err`, but didn't use them

2017-08-10 17:33 UTC, 8tomat8 commented on settingService/blockUser.go
>  	return nil, err
How `nil` could be returned as type `bool`?

2017-08-10 17:33 UTC, 8tomat8 commented on server/modules/modules.go
> +	ok, err := settingService.BlockUnblockUser(*message)
Why are you trying to copy value to function if it require pointer? Have you tried to run this code?

2017-08-10 17:48 UTC, YAWAL commented on settingService/blockUser.go
>  	return nil, err
Fixed. In a case of failed function will return true, which means that message mustn't be sent.

2017-08-10 17:59 UTC, YAWAL commented on server/modules/modules.go
> +	ok, err := settingService.BlockUnblockUser(*message)
Yes, functions should accept pointer. A problem has been fixed.

2017-08-11 06:42 UTC, YAWAL commented on settingService/blockUser.go
> +func IsUserBlocked(request *messageService.Message) (isBlocked bool, err error) {
Checking for blocking has been added into Message function. Now, contact will be checked before showing a message for a user.

2017-08-11 07:15 UTC, 8tomat8 approved these changes

2017-08-11 07:40 UTC, merged

2017-08-11 20:53 UTC, KitlerUA commented on settingService/blockUser.go
>  	contactUser := request.Body.ReceiverName
Unresolved reference 'ReceiverName'
Body has type RawMessage. So you cannot get ReceiverName in this way

2017-08-11 20:53 UTC, KitlerUA commented on server/modules/modules.go
> +	err = coremessage.SendMessage(message, messageType)
Cannot use `coremessage.SendMessage(message, messageType) (type messageService.Message)` as type `error` in assignment