Minor fixing
bohdanlisovskyi/SSU-Golang-252-Chat pull request #5
Opened 2017-07-20 16:50 UTC by YAWAL

Native Go-logger has been changed to custom logger from package loger.Log

2017-07-20 17:00 UTC, justakit approved these changes

2017-07-22 14:14 UTC, 8tomat8 requested changes

2017-07-22 14:14 UTC, 8tomat8 commented on messageService/message.go
> +	"SSU-Golang-252-Chat/loger"
Here should be full package path.

2017-07-22 14:14 UTC, 8tomat8 commented on messageService/message_test.go
> +	"SSU-Golang-252-Chat/loger"
Here should be full package path.

2017-07-22 14:14 UTC, 8tomat8 commented on messageService/message_test.go
> +		loger.Log.Fatal("Error has occured: ", err)
Dont use app logger in tests. You have all required functionality in `t`

2017-07-23 12:45 UTC, YAWAL commented on messageService/message.go
> +	"SSU-Golang-252-Chat/loger"
Done

2017-07-23 12:46 UTC, YAWAL commented on messageService/message_test.go
> +	"SSU-Golang-252-Chat/loger"
Import has been deleted: custom logger won't use in test file.

2017-07-23 12:46 UTC, YAWAL commented on messageService/message_test.go
> +		loger.Log.Fatal("Error has occured: ", err)
Import has been deleted: custom logger won't use in test file.

2017-07-25 07:02 UTC, 8tomat8 approved these changes

2017-07-25 07:04 UTC, merged